# Databricks notebook source
# Imports
import pyspark.sql.functions as f
from pyspark.sql.types import *
from pyspark.sql.column import Column, _to_java_column
from pyspark.sql.types import _parse_datatype_json_string
from pyspark.sql.window import Window
from itertools import chain

# COMMAND ----------

# Global variables
CURRENT_USER = dbutils.notebook.entry_point.getDbutils().notebook().getContext().tags().apply('user')
CATALOG = 'kinatrax'
DATABASE_L = 'landing'
DATABASE_B = 'bronze'
DATABASE_S = 'silver'
DATABASE_G = 'gold'
SCHEMA_BASE = f'dbfs:/user/{CURRENT_USER}/{CATALOG}'
CHECKPOINT_BASE = f'dbfs:/user/{CURRENT_USER}/{CATALOG}'

# COMMAND ----------

# DBTITLE 1,Create the kinatrax catalog
spark.sql(f"""
          CREATE CATALOG IF NOT EXISTS {CATALOG}
          COMMENT 'Catalog for storing and processing all Kinatrax data';
          """)

spark.sql(f"""
          ALTER CATALOG {CATALOG}
          SET TAGS ('removeAfter' = '20241101');
          """)

spark.sql(f"""
          USE CATALOG {CATALOG};
          """)

# COMMAND ----------

# DBTITLE 1,Create the landing, bonze, silver and gold databases
spark.sql(f"""
          CREATE DATABASE IF NOT EXISTS {CATALOG}.{DATABASE_L}
          COMMENT 'Landing database for storing raw Kinatrax extracts from servers in a UC volume';
          """)

spark.sql(f"""
          CREATE DATABASE IF NOT EXISTS {CATALOG}.{DATABASE_B}
          COMMENT 'Bronze database for copies of Kinatrax landing tables, augmented with metadata fields from folder paths. Flexible schemas in case source formats change using Autoloader schema evolution with rescue';
          """)

spark.sql(f"""
          CREATE DATABASE IF NOT EXISTS {CATALOG}.{DATABASE_S}
          COMMENT 'Silver database for storing clean, denormalized Kinatrax data for analysis, with quality constraints met';
          """)

spark.sql(f"""
          CREATE DATABASE IF NOT EXISTS {CATALOG}.{DATABASE_G}
          COMMENT 'Gold database for serving aggregated Kinatrax data, KPIs etc. to front-end applications';
          """)

spark.sql(f"""
          USE DATABASE {DATABASE_S};
          """)

# COMMAND ----------

# DBTITLE 1,Create the silver batting_motion_sequence_batting_key_frames table with liquid clustering keys
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS batting_motion_sequence_batting_key_frames (
# MAGIC   GamePK BIGINT,
# MAGIC   ID BIGINT,
# MAGIC   PlayID STRING,
# MAGIC   Weight BIGINT,
# MAGIC   KeyFrameNames STRING,
# MAGIC   AreKeyFramesDetected STRING,
# MAGIC   KeyFrameIndicesAdjusted INT,
# MAGIC   KeyFrameDetectionScores STRING,
# MAGIC   Timestamp DOUBLE,
# MAGIC   Hips_R11 DOUBLE,
# MAGIC   Hips_R12 DOUBLE,
# MAGIC   Hips_R13 DOUBLE,
# MAGIC   Hips_tx DOUBLE,
# MAGIC   Hips_R21 DOUBLE,
# MAGIC   Hips_R22 DOUBLE,
# MAGIC   Hips_R23 DOUBLE,
# MAGIC   Hips_ty DOUBLE,
# MAGIC   Hips_R31 DOUBLE,
# MAGIC   Hips_R32 DOUBLE,
# MAGIC   Hips_R33 DOUBLE,
# MAGIC   Hips_tz DOUBLE,
# MAGIC   Hips_M41 INT,
# MAGIC   Hips_M42 INT,
# MAGIC   Hips_M43 INT,
# MAGIC   Hips_M44 INT,
# MAGIC   JointSpine_R11 DOUBLE,
# MAGIC   JointSpine_R12 DOUBLE,
# MAGIC   JointSpine_R13 DOUBLE,
# MAGIC   JointSpine_tx DOUBLE,
# MAGIC   JointSpine_R21 DOUBLE,
# MAGIC   JointSpine_R22 DOUBLE,
# MAGIC   JointSpine_R23 DOUBLE,
# MAGIC   JointSpine_ty DOUBLE,
# MAGIC   JointSpine_R31 DOUBLE,
# MAGIC   JointSpine_R32 DOUBLE,
# MAGIC   JointSpine_R33 DOUBLE,
# MAGIC   JointSpine_tz DOUBLE,
# MAGIC   JointSpine_M41 INT,
# MAGIC   JointSpine_M42 INT,
# MAGIC   JointSpine_M43 INT,
# MAGIC   JointSpine_M44 INT,
# MAGIC   Spine_R11 DOUBLE,
# MAGIC   Spine_R12 DOUBLE,
# MAGIC   Spine_R13 DOUBLE,
# MAGIC   Spine_tx DOUBLE,
# MAGIC   Spine_R21 DOUBLE,
# MAGIC   Spine_R22 DOUBLE,
# MAGIC   Spine_R23 DOUBLE,
# MAGIC   Spine_ty DOUBLE,
# MAGIC   Spine_R31 DOUBLE,
# MAGIC   Spine_R32 DOUBLE,
# MAGIC   Spine_R33 DOUBLE,
# MAGIC   Spine_tz DOUBLE,
# MAGIC   Spine_M41 INT,
# MAGIC   Spine_M42 INT,
# MAGIC   Spine_M43 INT,
# MAGIC   Spine_M44 INT,
# MAGIC   Neck_R11 DOUBLE,
# MAGIC   Neck_R12 DOUBLE,
# MAGIC   Neck_R13 DOUBLE,
# MAGIC   Neck_tx DOUBLE,
# MAGIC   Neck_R21 DOUBLE,
# MAGIC   Neck_R22 DOUBLE,
# MAGIC   Neck_R23 DOUBLE,
# MAGIC   Neck_ty DOUBLE,
# MAGIC   Neck_R31 DOUBLE,
# MAGIC   Neck_R32 DOUBLE,
# MAGIC   Neck_R33 DOUBLE,
# MAGIC   Neck_tz DOUBLE,
# MAGIC   Neck_M41 INT,
# MAGIC   Neck_M42 INT,
# MAGIC   Neck_M43 INT,
# MAGIC   Neck_M44 INT,
# MAGIC   JointHead_R11 DOUBLE,
# MAGIC   JointHead_R12 DOUBLE,
# MAGIC   JointHead_R13 DOUBLE,
# MAGIC   JointHead_tx DOUBLE,
# MAGIC   JointHead_R21 DOUBLE,
# MAGIC   JointHead_R22 DOUBLE,
# MAGIC   JointHead_R23 DOUBLE,
# MAGIC   JointHead_ty DOUBLE,
# MAGIC   JointHead_R31 DOUBLE,
# MAGIC   JointHead_R32 DOUBLE,
# MAGIC   JointHead_R33 DOUBLE,
# MAGIC   JointHead_tz DOUBLE,
# MAGIC   JointHead_M41 INT,
# MAGIC   JointHead_M42 INT,
# MAGIC   JointHead_M43 INT,
# MAGIC   JointHead_M44 INT,
# MAGIC   Head_R11 DOUBLE,
# MAGIC   Head_R12 DOUBLE,
# MAGIC   Head_R13 DOUBLE,
# MAGIC   Head_tx DOUBLE,
# MAGIC   Head_R21 DOUBLE,
# MAGIC   Head_R22 DOUBLE,
# MAGIC   Head_R23 DOUBLE,
# MAGIC   Head_ty DOUBLE,
# MAGIC   Head_R31 DOUBLE,
# MAGIC   Head_R32 DOUBLE,
# MAGIC   Head_R33 DOUBLE,
# MAGIC   Head_tz DOUBLE,
# MAGIC   Head_M41 INT,
# MAGIC   Head_M42 INT,
# MAGIC   Head_M43 INT,
# MAGIC   Head_M44 INT,
# MAGIC   JointLeftUpperArm_R11 DOUBLE,
# MAGIC   JointLeftUpperArm_R12 DOUBLE,
# MAGIC   JointLeftUpperArm_R13 DOUBLE,
# MAGIC   JointLeftUpperArm_tx DOUBLE,
# MAGIC   JointLeftUpperArm_R21 DOUBLE,
# MAGIC   JointLeftUpperArm_R22 DOUBLE,
# MAGIC   JointLeftUpperArm_R23 DOUBLE,
# MAGIC   JointLeftUpperArm_ty DOUBLE,
# MAGIC   JointLeftUpperArm_R31 DOUBLE,
# MAGIC   JointLeftUpperArm_R32 DOUBLE,
# MAGIC   JointLeftUpperArm_R33 DOUBLE,
# MAGIC   JointLeftUpperArm_tz DOUBLE,
# MAGIC   JointLeftUpperArm_M41 INT,
# MAGIC   JointLeftUpperArm_M42 INT,
# MAGIC   JointLeftUpperArm_M43 INT,
# MAGIC   JointLeftUpperArm_M44 INT,
# MAGIC   LeftUpperArm_R11 DOUBLE,
# MAGIC   LeftUpperArm_R12 DOUBLE,
# MAGIC   LeftUpperArm_R13 DOUBLE,
# MAGIC   LeftUpperArm_tx DOUBLE,
# MAGIC   LeftUpperArm_R21 DOUBLE,
# MAGIC   LeftUpperArm_R22 DOUBLE,
# MAGIC   LeftUpperArm_R23 DOUBLE,
# MAGIC   LeftUpperArm_ty DOUBLE,
# MAGIC   LeftUpperArm_R31 DOUBLE,
# MAGIC   LeftUpperArm_R32 DOUBLE,
# MAGIC   LeftUpperArm_R33 DOUBLE,
# MAGIC   LeftUpperArm_tz DOUBLE,
# MAGIC   LeftUpperArm_M41 INT,
# MAGIC   LeftUpperArm_M42 INT,
# MAGIC   LeftUpperArm_M43 INT,
# MAGIC   LeftUpperArm_M44 INT,
# MAGIC   LeftForearm_R11 DOUBLE,
# MAGIC   LeftForearm_R12 DOUBLE,
# MAGIC   LeftForearm_R13 DOUBLE,
# MAGIC   LeftForearm_tx DOUBLE,
# MAGIC   LeftForearm_R21 DOUBLE,
# MAGIC   LeftForearm_R22 DOUBLE,
# MAGIC   LeftForearm_R23 DOUBLE,
# MAGIC   LeftForearm_ty DOUBLE,
# MAGIC   LeftForearm_R31 DOUBLE,
# MAGIC   LeftForearm_R32 DOUBLE,
# MAGIC   LeftForearm_R33 DOUBLE,
# MAGIC   LeftForearm_tz DOUBLE,
# MAGIC   LeftForearm_M41 INT,
# MAGIC   LeftForearm_M42 INT,
# MAGIC   LeftForearm_M43 INT,
# MAGIC   LeftForearm_M44 INT,
# MAGIC   LeftWrist_R11 DOUBLE,
# MAGIC   LeftWrist_R12 DOUBLE,
# MAGIC   LeftWrist_R13 DOUBLE,
# MAGIC   LeftWrist_tx DOUBLE,
# MAGIC   LeftWrist_R21 DOUBLE,
# MAGIC   LeftWrist_R22 DOUBLE,
# MAGIC   LeftWrist_R23 DOUBLE,
# MAGIC   LeftWrist_ty DOUBLE,
# MAGIC   LeftWrist_R31 DOUBLE,
# MAGIC   LeftWrist_R32 DOUBLE,
# MAGIC   LeftWrist_R33 DOUBLE,
# MAGIC   LeftWrist_tz DOUBLE,
# MAGIC   LeftWrist_M41 INT,
# MAGIC   LeftWrist_M42 INT,
# MAGIC   LeftWrist_M43 INT,
# MAGIC   LeftWrist_M44 INT,
# MAGIC   LeftHand_R11 DOUBLE,
# MAGIC   LeftHand_R12 DOUBLE,
# MAGIC   LeftHand_R13 DOUBLE,
# MAGIC   LeftHand_tx DOUBLE,
# MAGIC   LeftHand_R21 DOUBLE,
# MAGIC   LeftHand_R22 DOUBLE,
# MAGIC   LeftHand_R23 DOUBLE,
# MAGIC   LeftHand_ty DOUBLE,
# MAGIC   LeftHand_R31 DOUBLE,
# MAGIC   LeftHand_R32 DOUBLE,
# MAGIC   LeftHand_R33 DOUBLE,
# MAGIC   LeftHand_tz DOUBLE,
# MAGIC   LeftHand_M41 INT,
# MAGIC   LeftHand_M42 INT,
# MAGIC   LeftHand_M43 INT,
# MAGIC   LeftHand_M44 INT,
# MAGIC   JointRightUpperArm_R11 DOUBLE,
# MAGIC   JointRightUpperArm_R12 DOUBLE,
# MAGIC   JointRightUpperArm_R13 DOUBLE,
# MAGIC   JointRightUpperArm_tx DOUBLE,
# MAGIC   JointRightUpperArm_R21 DOUBLE,
# MAGIC   JointRightUpperArm_R22 DOUBLE,
# MAGIC   JointRightUpperArm_R23 DOUBLE,
# MAGIC   JointRightUpperArm_ty DOUBLE,
# MAGIC   JointRightUpperArm_R31 DOUBLE,
# MAGIC   JointRightUpperArm_R32 DOUBLE,
# MAGIC   JointRightUpperArm_R33 DOUBLE,
# MAGIC   JointRightUpperArm_tz DOUBLE,
# MAGIC   JointRightUpperArm_M41 INT,
# MAGIC   JointRightUpperArm_M42 INT,
# MAGIC   JointRightUpperArm_M43 INT,
# MAGIC   JointRightUpperArm_M44 INT,
# MAGIC   RightUpperArm_R11 DOUBLE,
# MAGIC   RightUpperArm_R12 DOUBLE,
# MAGIC   RightUpperArm_R13 DOUBLE,
# MAGIC   RightUpperArm_tx DOUBLE,
# MAGIC   RightUpperArm_R21 DOUBLE,
# MAGIC   RightUpperArm_R22 DOUBLE,
# MAGIC   RightUpperArm_R23 DOUBLE,
# MAGIC   RightUpperArm_ty DOUBLE,
# MAGIC   RightUpperArm_R31 DOUBLE,
# MAGIC   RightUpperArm_R32 DOUBLE,
# MAGIC   RightUpperArm_R33 DOUBLE,
# MAGIC   RightUpperArm_tz DOUBLE,
# MAGIC   RightUpperArm_M41 INT,
# MAGIC   RightUpperArm_M42 INT,
# MAGIC   RightUpperArm_M43 INT,
# MAGIC   RightUpperArm_M44 INT,
# MAGIC   RightForearm_R11 DOUBLE,
# MAGIC   RightForearm_R12 DOUBLE,
# MAGIC   RightForearm_R13 DOUBLE,
# MAGIC   RightForearm_tx DOUBLE,
# MAGIC   RightForearm_R21 DOUBLE,
# MAGIC   RightForearm_R22 DOUBLE,
# MAGIC   RightForearm_R23 DOUBLE,
# MAGIC   RightForearm_ty DOUBLE,
# MAGIC   RightForearm_R31 DOUBLE,
# MAGIC   RightForearm_R32 DOUBLE,
# MAGIC   RightForearm_R33 DOUBLE,
# MAGIC   RightForearm_tz DOUBLE,
# MAGIC   RightForearm_M41 INT,
# MAGIC   RightForearm_M42 INT,
# MAGIC   RightForearm_M43 INT,
# MAGIC   RightForearm_M44 INT,
# MAGIC   RightWrist_R11 DOUBLE,
# MAGIC   RightWrist_R12 DOUBLE,
# MAGIC   RightWrist_R13 DOUBLE,
# MAGIC   RightWrist_tx DOUBLE,
# MAGIC   RightWrist_R21 DOUBLE,
# MAGIC   RightWrist_R22 DOUBLE,
# MAGIC   RightWrist_R23 DOUBLE,
# MAGIC   RightWrist_ty DOUBLE,
# MAGIC   RightWrist_R31 DOUBLE,
# MAGIC   RightWrist_R32 DOUBLE,
# MAGIC   RightWrist_R33 DOUBLE,
# MAGIC   RightWrist_tz DOUBLE,
# MAGIC   RightWrist_M41 INT,
# MAGIC   RightWrist_M42 INT,
# MAGIC   RightWrist_M43 INT,
# MAGIC   RightWrist_M44 INT,
# MAGIC   RightHand_R11 DOUBLE,
# MAGIC   RightHand_R12 DOUBLE,
# MAGIC   RightHand_R13 DOUBLE,
# MAGIC   RightHand_tx DOUBLE,
# MAGIC   RightHand_R21 DOUBLE,
# MAGIC   RightHand_R22 DOUBLE,
# MAGIC   RightHand_R23 DOUBLE,
# MAGIC   RightHand_ty DOUBLE,
# MAGIC   RightHand_R31 DOUBLE,
# MAGIC   RightHand_R32 DOUBLE,
# MAGIC   RightHand_R33 DOUBLE,
# MAGIC   RightHand_tz DOUBLE,
# MAGIC   RightHand_M41 INT,
# MAGIC   RightHand_M42 INT,
# MAGIC   RightHand_M43 INT,
# MAGIC   RightHand_M44 INT,
# MAGIC   JointLeftThigh_R11 DOUBLE,
# MAGIC   JointLeftThigh_R12 DOUBLE,
# MAGIC   JointLeftThigh_R13 DOUBLE,
# MAGIC   JointLeftThigh_tx DOUBLE,
# MAGIC   JointLeftThigh_R21 DOUBLE,
# MAGIC   JointLeftThigh_R22 DOUBLE,
# MAGIC   JointLeftThigh_R23 DOUBLE,
# MAGIC   JointLeftThigh_ty DOUBLE,
# MAGIC   JointLeftThigh_R31 DOUBLE,
# MAGIC   JointLeftThigh_R32 DOUBLE,
# MAGIC   JointLeftThigh_R33 DOUBLE,
# MAGIC   JointLeftThigh_tz DOUBLE,
# MAGIC   JointLeftThigh_M41 INT,
# MAGIC   JointLeftThigh_M42 INT,
# MAGIC   JointLeftThigh_M43 INT,
# MAGIC   JointLeftThigh_M44 INT,
# MAGIC   LeftThigh_R11 DOUBLE,
# MAGIC   LeftThigh_R12 DOUBLE,
# MAGIC   LeftThigh_R13 DOUBLE,
# MAGIC   LeftThigh_tx DOUBLE,
# MAGIC   LeftThigh_R21 DOUBLE,
# MAGIC   LeftThigh_R22 DOUBLE,
# MAGIC   LeftThigh_R23 DOUBLE,
# MAGIC   LeftThigh_ty DOUBLE,
# MAGIC   LeftThigh_R31 DOUBLE,
# MAGIC   LeftThigh_R32 DOUBLE,
# MAGIC   LeftThigh_R33 DOUBLE,
# MAGIC   LeftThigh_tz DOUBLE,
# MAGIC   LeftThigh_M41 INT,
# MAGIC   LeftThigh_M42 INT,
# MAGIC   LeftThigh_M43 INT,
# MAGIC   LeftThigh_M44 INT,
# MAGIC   LeftShin_R11 DOUBLE,
# MAGIC   LeftShin_R12 DOUBLE,
# MAGIC   LeftShin_R13 DOUBLE,
# MAGIC   LeftShin_tx DOUBLE,
# MAGIC   LeftShin_R21 DOUBLE,
# MAGIC   LeftShin_R22 DOUBLE,
# MAGIC   LeftShin_R23 DOUBLE,
# MAGIC   LeftShin_ty DOUBLE,
# MAGIC   LeftShin_R31 DOUBLE,
# MAGIC   LeftShin_R32 DOUBLE,
# MAGIC   LeftShin_R33 DOUBLE,
# MAGIC   LeftShin_tz DOUBLE,
# MAGIC   LeftShin_M41 INT,
# MAGIC   LeftShin_M42 INT,
# MAGIC   LeftShin_M43 INT,
# MAGIC   LeftShin_M44 INT,
# MAGIC   LeftAnkle_R11 DOUBLE,
# MAGIC   LeftAnkle_R12 DOUBLE,
# MAGIC   LeftAnkle_R13 DOUBLE,
# MAGIC   LeftAnkle_tx DOUBLE,
# MAGIC   LeftAnkle_R21 DOUBLE,
# MAGIC   LeftAnkle_R22 DOUBLE,
# MAGIC   LeftAnkle_R23 DOUBLE,
# MAGIC   LeftAnkle_ty DOUBLE,
# MAGIC   LeftAnkle_R31 DOUBLE,
# MAGIC   LeftAnkle_R32 DOUBLE,
# MAGIC   LeftAnkle_R33 DOUBLE,
# MAGIC   LeftAnkle_tz DOUBLE,
# MAGIC   LeftAnkle_M41 INT,
# MAGIC   LeftAnkle_M42 INT,
# MAGIC   LeftAnkle_M43 INT,
# MAGIC   LeftAnkle_M44 INT,
# MAGIC   LeftFoot_R11 DOUBLE,
# MAGIC   LeftFoot_R12 DOUBLE,
# MAGIC   LeftFoot_R13 DOUBLE,
# MAGIC   LeftFoot_tx DOUBLE,
# MAGIC   LeftFoot_R21 DOUBLE,
# MAGIC   LeftFoot_R22 DOUBLE,
# MAGIC   LeftFoot_R23 DOUBLE,
# MAGIC   LeftFoot_ty DOUBLE,
# MAGIC   LeftFoot_R31 DOUBLE,
# MAGIC   LeftFoot_R32 DOUBLE,
# MAGIC   LeftFoot_R33 DOUBLE,
# MAGIC   LeftFoot_tz DOUBLE,
# MAGIC   LeftFoot_M41 INT,
# MAGIC   LeftFoot_M42 INT,
# MAGIC   LeftFoot_M43 INT,
# MAGIC   LeftFoot_M44 INT,
# MAGIC   JointRightThigh_R11 DOUBLE,
# MAGIC   JointRightThigh_R12 DOUBLE,
# MAGIC   JointRightThigh_R13 DOUBLE,
# MAGIC   JointRightThigh_tx DOUBLE,
# MAGIC   JointRightThigh_R21 DOUBLE,
# MAGIC   JointRightThigh_R22 DOUBLE,
# MAGIC   JointRightThigh_R23 DOUBLE,
# MAGIC   JointRightThigh_ty DOUBLE,
# MAGIC   JointRightThigh_R31 DOUBLE,
# MAGIC   JointRightThigh_R32 DOUBLE,
# MAGIC   JointRightThigh_R33 DOUBLE,
# MAGIC   JointRightThigh_tz DOUBLE,
# MAGIC   JointRightThigh_M41 INT,
# MAGIC   JointRightThigh_M42 INT,
# MAGIC   JointRightThigh_M43 INT,
# MAGIC   JointRightThigh_M44 INT,
# MAGIC   RightThigh_R11 DOUBLE,
# MAGIC   RightThigh_R12 DOUBLE,
# MAGIC   RightThigh_R13 DOUBLE,
# MAGIC   RightThigh_tx DOUBLE,
# MAGIC   RightThigh_R21 DOUBLE,
# MAGIC   RightThigh_R22 DOUBLE,
# MAGIC   RightThigh_R23 DOUBLE,
# MAGIC   RightThigh_ty DOUBLE,
# MAGIC   RightThigh_R31 DOUBLE,
# MAGIC   RightThigh_R32 DOUBLE,
# MAGIC   RightThigh_R33 DOUBLE,
# MAGIC   RightThigh_tz DOUBLE,
# MAGIC   RightThigh_M41 INT,
# MAGIC   RightThigh_M42 INT,
# MAGIC   RightThigh_M43 INT,
# MAGIC   RightThigh_M44 INT,
# MAGIC   RightShin_R11 DOUBLE,
# MAGIC   RightShin_R12 DOUBLE,
# MAGIC   RightShin_R13 DOUBLE,
# MAGIC   RightShin_tx DOUBLE,
# MAGIC   RightShin_R21 DOUBLE,
# MAGIC   RightShin_R22 DOUBLE,
# MAGIC   RightShin_R23 DOUBLE,
# MAGIC   RightShin_ty DOUBLE,
# MAGIC   RightShin_R31 DOUBLE,
# MAGIC   RightShin_R32 DOUBLE,
# MAGIC   RightShin_R33 DOUBLE,
# MAGIC   RightShin_tz DOUBLE,
# MAGIC   RightShin_M41 INT,
# MAGIC   RightShin_M42 INT,
# MAGIC   RightShin_M43 INT,
# MAGIC   RightShin_M44 INT,
# MAGIC   RightAnkle_R11 DOUBLE,
# MAGIC   RightAnkle_R12 DOUBLE,
# MAGIC   RightAnkle_R13 DOUBLE,
# MAGIC   RightAnkle_tx DOUBLE,
# MAGIC   RightAnkle_R21 DOUBLE,
# MAGIC   RightAnkle_R22 DOUBLE,
# MAGIC   RightAnkle_R23 DOUBLE,
# MAGIC   RightAnkle_ty DOUBLE,
# MAGIC   RightAnkle_R31 DOUBLE,
# MAGIC   RightAnkle_R32 DOUBLE,
# MAGIC   RightAnkle_R33 DOUBLE,
# MAGIC   RightAnkle_tz DOUBLE,
# MAGIC   RightAnkle_M41 INT,
# MAGIC   RightAnkle_M42 INT,
# MAGIC   RightAnkle_M43 INT,
# MAGIC   RightAnkle_M44 INT,
# MAGIC   RightFoot_R11 DOUBLE,
# MAGIC   RightFoot_R12 DOUBLE,
# MAGIC   RightFoot_R13 DOUBLE,
# MAGIC   RightFoot_tx DOUBLE,
# MAGIC   RightFoot_R21 DOUBLE,
# MAGIC   RightFoot_R22 DOUBLE,
# MAGIC   RightFoot_R23 DOUBLE,
# MAGIC   RightFoot_ty DOUBLE,
# MAGIC   RightFoot_R31 DOUBLE,
# MAGIC   RightFoot_R32 DOUBLE,
# MAGIC   RightFoot_R33 DOUBLE,
# MAGIC   RightFoot_tz DOUBLE,
# MAGIC   RightFoot_M41 INT,
# MAGIC   RightFoot_M42 INT,
# MAGIC   RightFoot_M43 INT,
# MAGIC   RightFoot_M44 INT,
# MAGIC   Knob_R11 DOUBLE,
# MAGIC   Knob_R12 DOUBLE,
# MAGIC   Knob_R13 DOUBLE,
# MAGIC   Knob_tx DOUBLE,
# MAGIC   Knob_R21 DOUBLE,
# MAGIC   Knob_R22 DOUBLE,
# MAGIC   Knob_R23 DOUBLE,
# MAGIC   Knob_ty DOUBLE,
# MAGIC   Knob_R31 DOUBLE,
# MAGIC   Knob_R32 DOUBLE,
# MAGIC   Knob_R33 DOUBLE,
# MAGIC   Knob_tz DOUBLE,
# MAGIC   Knob_M41 INT,
# MAGIC   Knob_M42 INT,
# MAGIC   Knob_M43 INT,
# MAGIC   Knob_M44 INT,
# MAGIC   Top_R11 DOUBLE,
# MAGIC   Top_R12 DOUBLE,
# MAGIC   Top_R13 DOUBLE,
# MAGIC   Top_tx DOUBLE,
# MAGIC   Top_R21 DOUBLE,
# MAGIC   Top_R22 DOUBLE,
# MAGIC   Top_R23 DOUBLE,
# MAGIC   Top_ty DOUBLE,
# MAGIC   Top_R31 DOUBLE,
# MAGIC   Top_R32 DOUBLE,
# MAGIC   Top_R33 DOUBLE,
# MAGIC   Top_tz DOUBLE,
# MAGIC   Top_M41 INT,
# MAGIC   Top_M42 INT,
# MAGIC   Top_M43 INT,
# MAGIC   Top_M44 INT,
# MAGIC   Center_R11 INT,
# MAGIC   Center_R12 INT,
# MAGIC   Center_R13 INT,
# MAGIC   Center_tx DOUBLE,
# MAGIC   Center_R21 INT,
# MAGIC   Center_R22 INT,
# MAGIC   Center_R23 INT,
# MAGIC   Center_ty DOUBLE,
# MAGIC   Center_R31 INT,
# MAGIC   Center_R32 INT,
# MAGIC   Center_R33 INT,
# MAGIC   Center_tz DOUBLE,
# MAGIC   Center_M41 INT,
# MAGIC   Center_M42 INT,
# MAGIC   Center_M43 INT,
# MAGIC   Center_M44 INT,
# MAGIC   input_event STRING,
# MAGIC   TimestampRounded INT
# MAGIC   )
# MAGIC USING DELTA
# MAGIC CLUSTER BY (ID, GamePK, PlayID)
# MAGIC COMMENT 'The \'batting_motion_sequence_batting_key_frames\' table captures key frames of a batting motion sequence for the batter, bat and ball, including the types of key frames and whether they were detected or not. It also includes scores for key frame detection, timestamps of when these key frames occurred, and specific measurements of the joints such as R11, R12, R13, etc. This data can be useful for studying human motion, analyzing sports performance, or developing artificial intelligence algorithms for sports analysis.';

# COMMAND ----------

# DBTITLE 1,Create the silver batting_motion_sequence_batting_master table with liquid clustering keys
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS batting_motion_sequence_batting_master (
# MAGIC   GamePK BIGINT,
# MAGIC   ID BIGINT,
# MAGIC   PlayID STRING,
# MAGIC   Weight BIGINT,
# MAGIC   Timestamp DOUBLE,
# MAGIC   input_event STRING,
# MAGIC   hips_zip MAP<STRING, DOUBLE>,
# MAGIC   spine_zip MAP<STRING, DOUBLE>,
# MAGIC   neck_zip MAP<STRING, DOUBLE>,
# MAGIC   head_zip MAP<STRING, DOUBLE>,
# MAGIC   leftupperarm_zip MAP<STRING, DOUBLE>,
# MAGIC   leftforearm_zip MAP<STRING, DOUBLE>,
# MAGIC   leftwrist_zip MAP<STRING, DOUBLE>,
# MAGIC   lefthand_zip MAP<STRING, DOUBLE>,
# MAGIC   rightupperarm_zip MAP<STRING, DOUBLE>,
# MAGIC   rightforearm_zip MAP<STRING, DOUBLE>,
# MAGIC   rightwrist_zip MAP<STRING, DOUBLE>,
# MAGIC   righthand_zip MAP<STRING, DOUBLE>,
# MAGIC   leftthigh_zip MAP<STRING, DOUBLE>,
# MAGIC   leftshin_zip MAP<STRING, DOUBLE>,
# MAGIC   leftankle_zip MAP<STRING, DOUBLE>,
# MAGIC   leftfoot_zip MAP<STRING, DOUBLE>,
# MAGIC   rightthigh_zip MAP<STRING, DOUBLE>,
# MAGIC   rightshin_zip MAP<STRING, DOUBLE>,
# MAGIC   rightankle_zip MAP<STRING, DOUBLE>,
# MAGIC   rightfoot_zip MAP<STRING, DOUBLE>,
# MAGIC   JointSpine_zip MAP<STRING, DOUBLE>,
# MAGIC   JointHead_zip MAP<STRING, DOUBLE>,
# MAGIC   JointLeftUpperArm_zip MAP<STRING, DOUBLE>,
# MAGIC   JointRightUpperArm_zip MAP<STRING, DOUBLE>,
# MAGIC   JointLeftThigh_zip MAP<STRING, DOUBLE>,
# MAGIC   JointRightThigh_zip MAP<STRING, DOUBLE>,
# MAGIC   Knob_zip MAP<STRING, DOUBLE>,
# MAGIC   Top_zip MAP<STRING, DOUBLE>,
# MAGIC   Center_zip MAP<STRING, DOUBLE>)
# MAGIC USING DELTA
# MAGIC CLUSTER BY (ID, GamePK, PlayID)
# MAGIC COMMENT 'The \'batting_motion_sequence_batting_master\' table captures the sequence of motions involved in a baseball swing, specifically for the batter, bat and ball. The data includes timestamps of each frame, along with corresponding values for each transformation matrix and confidence score, bonefitting error and tracking state. This information can be used to analyze and understand the batting motion, identify patterns or inconsistencies in the swing, and potentially aid in the development of batting strategies or training regimens.';
